name: 'Build and Publish Docker Image'

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish to GHCR (only works on main branch)'
        type: 'boolean'
        default: false
      tag:
        description: 'The tag to release from'
        required: true 
        type: 'string'


env:
  REGISTRY: 'ghcr.io'
  IMAGE_NAME: '${{ github.repository }}'

jobs:
  build-and-push-to-ghcr:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      packages: 'write'

    steps:
      - name: 'Checkout repository'
        uses: 'actions/checkout@v4'

      - name: 'Set up QEMU'
        uses: 'docker/setup-qemu-action@v3'

      - name: 'Set up Docker Buildx'
        uses: 'docker/setup-buildx-action@v3'

      - name: 'Determine if should push'
        id: 'should-push'
        run: |
          SHOULD_PUSH="false"
          if [[ "${{ github.event_name }}" == "push" && "${{ startsWith(github.ref, 'refs/tags/v') }}" == "true" ]]; then
            SHOULD_PUSH="true"
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            SHOULD_PUSH="true"
          elif [[ "${{ github.event.inputs.publish }}" == "true" ]]; then
            SHOULD_PUSH="true"
          fi
          echo "push=${SHOULD_PUSH}" >> "$GITHUB_OUTPUT"

      - name: 'Extract metadata (tags, labels) for Docker'
        id: 'meta'
        uses: 'docker/metadata-action@v5'
        with:
          images: '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}'
          tags: |
            type=ref,event= '${{ github.event.inputs.tag }}'
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix=sha-,format=short

      - name: 'Log in to the Container registry'
        if: steps.should-push.outputs.push == 'true'
        uses: 'docker/login-action@v3'
        with:
          registry: '${{ env.REGISTRY }}'
          username: '${{ github.actor }}'
          password: '${{ secrets.GITHUB_TOKEN }}'

      - name: 'Build and push Docker image'
        id: 'build-and-push'
        uses: 'docker/build-push-action@v6'
        with:
          context: '.'
          platforms: 'linux/amd64,linux/arm64'
          push: '${{ steps.should-push.outputs.push }}'
          tags: '${{ steps.meta.outputs.tags }}'
          labels: '${{ steps.meta.outputs.labels }}'
          build-args: |
            CLI_VERSION_ARG=${{ github.sha }}
